# LAPTOP DATA CLEANING

## Business Understanding

Laptop prices vary depending on their specifications, features, and brands. Understanding the factors associated with laptop prices can help consumers make informed purchasing decisions.

### Business Question

What factors influence laptop prices in the global market?

In [6]:
# import necessary dependancies
import pandas as pd
import opendatasets as od
import os

## Data understanding

In [4]:
data_url="https://www.kaggle.com/datasets/mdriazhossain/global-laptop-selling-dataset"

# download data
od.download(data_url,"../data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Dataset URL: https://www.kaggle.com/datasets/mdriazhossain/global-laptop-selling-dataset
Downloading global-laptop-selling-dataset.zip to ../data/global-laptop-selling-dataset

100%|██████████| 27.8k/27.8k [00:00<00:00, 23.9MB/s]

In [7]:
#list downloaded files
os.listdir("../data/global-laptop-selling-dataset")

['global_laptop_selling_data.csv']

In [9]:
# load data
laptop_df=pd.read_csv("../data/global-laptop-selling-dataset/global_laptop_selling_data.csv")

In [10]:
# display first 5 rows
laptop_df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [11]:
# display last 5 rows
laptop_df.tail()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.0
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.0
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.0
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.0

In [16]:
# dispay number of rows and columns
laptop_df.shape

(1303, 13)

The data has 1303 rows and 13 columns

In [17]:
# get general summary of the data
laptop_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Memory            1303 non-null   str
 9   Gpu               1303 non-null   str
 10  OpSys             1303 non-null   str
 11  Weight            1303 non-null   str
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(10)
memory usage: 132.5 KB

Their are no missing values

In [18]:
# check for duplicates
laptop_df.duplicated().sum()

np.int64(0)

In [19]:
# list unique values in product
laptop_df["Product"].unique()

<StringArray>
[                              'MacBook Pro',
                               'Macbook Air',
                                    '250 G6',
                                  'Aspire 3',
                           'ZenBook UX430UN',
                                   'Swift 3',
                             'Inspiron 3567',
                               'MacBook 12"',
                         'IdeaPad 320-15IKB',
                                    'XPS 13',
 ...
                               'GE62 Apache',
                            'Yoga 500-14IBD',
                      'ZenBook UX305CA-UBM1',
                            'Aspire ES1-531',
                       'Pavilion 15-AW003nv',
                          'Stream 11-Y000na',
 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce',
                            'Yoga 500-14ISK',
       '15-AC110nv (i7-6500U/6GB/1TB/Radeon',
       'X553SA-XX031T (N3050/4GB/500GB/W10)']
Length: 618, dtype: str

The data has no duplicates

### Cleaning Tasks

1. **ScreenResolution:** Extract the screen resolution into separate `ResolutionWidth` and `ResolutionHeight` columns and convert both to integers. Retain the `DisplayFeatures` in a separate column.

2. **RAM:** Remove the unit (GB) and convert the RAM capacity to an integer.

3. **Memory:** Separate storage capacity from storage type into distinct columns. Convert the storage capacity to a numeric format.

4. **CPU:** Extract the CPU brand, series, model, and clock speed into separate columns. Convert clock speed to a numeric data type.

5. **GPU:** Extract the GPU brand, series, and model into separate columns .

6. **Weight:** Remove the unit (kg) and convert weight to a float.
7. **Product**: Remove redundant hardware specifications embedded in product names while preserving the actual laptop model names.
8. Drop  **ScreenResolution:** after separating `ResolutionWidth` and `ResolutionHeight` and `DisplayFeatures`

## Cleaning

In [50]:
( 
 laptop_df.assign(
     Product=lambda x:x["Product"].str.replace(r"\(.*","",regex=True).str.strip(),
     ResolutionWidth=lambda x: x["ScreenResolution"].str.extract(r"(\d+)(?=[*x])").astype("int64"),
     ResolutionHeight=lambda x:x["ScreenResolution"].str.extract(r"(?<=[*x])(\d+)").astype("int64"),
     DisplayFeatures=lambda x:x["ScreenResolution"].str.extract(r"^(.*?)\s*\d+[*x]\d+"),
     CpuBrand=lambda x:x["Cpu"].str.extract(r"^(\w+)"),
     ClockSpeed=lambda x:x["Cpu"].str.extract(r"(\d+(?:\.\d+)?)GHz").astype(float),
     Ram=lambda x:x["Ram"].str.replace("GB","").astype(int)
     
     
     
 ).drop(columns=["ScreenResolution"])
   
)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,ResolutionWidth,ResolutionHeight,DisplayFeatures,CpuBrand,ClockSpeed
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,2560,1600,IPS Panel Retina Display,Intel,2.3
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,1440,900,,Intel,1.8
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,1920,1080,Full HD,Intel,2.5
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,2880,1800,IPS Panel Retina Display,Intel,2.7
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,2560,1600,IPS Panel Retina Display,Intel,3.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,1920,1080,IPS Panel Full HD / Touchscreen,Intel,2.5
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,3200,1800,IPS Panel Quad HD+ / Touchscreen,Intel,2.5
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,1366,768,,Intel,1.6
1301,1319,HP,15-AC110nv,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,1366,768,,Intel,2.5
1302,1320,Asus,X553SA-XX031T,Notebook,15.6,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,1366,768,,Intel,1.6

In [ ]:
SSD_CapacityGB=laptop_df["Memory"].str.extract(r"(\d+\w{2})\s*\SSD")

          0
0     128GB
1       NaN
2     256GB
3     512GB
4     256GB
...     ...
1298  128GB
1299  512GB
1300    NaN
1301    NaN
1302    NaN

[1303 rows x 1 columns]

In [58]:
laptop_df["Memory"].unique()

<StringArray>
[                    '128GB SSD',           '128GB Flash Storage',
                     '256GB SSD',                     '512GB SSD',
                     '500GB HDD',           '256GB Flash Storage',
                       '1TB HDD',            '32GB Flash Storage',
          '128GB SSD +  1TB HDD',        '256GB SSD +  256GB SSD',
            '64GB Flash Storage',          '256GB SSD +  1TB HDD',
          '256GB SSD +  2TB HDD',                      '32GB SSD',
                       '2TB HDD',                      '64GB SSD',
                  '1.0TB Hybrid',          '512GB SSD +  1TB HDD',
                       '1TB SSD',        '256GB SSD +  500GB HDD',
          '128GB SSD +  2TB HDD',        '512GB SSD +  512GB SSD',
                      '16GB SSD',            '16GB Flash Storage',
        '512GB SSD +  256GB SSD',          '512GB SSD +  2TB HDD',
 '64GB Flash Storage +  1TB HDD',                     '180GB SSD',
            '1TB HDD +  1TB HDD',                      '32GB HDD',
            '1TB SSD +  1TB HDD',           '512GB Flash Storage',
                     '128GB HDD',                     '240GB SSD',
                       '8GB SSD',                  '508GB Hybrid',
                     '1.0TB HDD',     '512GB SSD +  1.0TB Hybrid',
     '256GB SSD +  1.0TB Hybrid']
Length: 39, dtype: str

In [ ]:
HDD_CapacityGB=laptop_df["Memory"].str.extract(r"(\d+\w{2})\s*HDD")

          0
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
1298    NaN
1299    NaN
1300    NaN
1301    1TB
1302  500GB

[1303 rows x 1 columns]

In [75]:
FlashStorageGB=laptop_df["Memory"].str.extract(r"(\d+\w{2})\s*Flash\s*Storage")
FlashStorageGB

          0
0       NaN
1     128GB
2       NaN
3       NaN
4       NaN
...     ...
1298    NaN
1299    NaN
1300   64GB
1301    NaN
1302    NaN

[1303 rows x 1 columns]

64GB Flash Storage